[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
major_version = 15

[db.pooler]
enabled = true
pool_mode = "transaction"
default_pool_size = 10
max_client_conn = 100

[analytics]
enabled = false

[realtime]
enabled = true

[auth]
enabled = true
enable_signup = true
enable_anonymous_sign_ins = true
